# Generated by Django 4.0.3 on 2022-04-15 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_history_plan_alter_history_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.plan'),
        ),
    ]
