# Generated by Django 4.0.3 on 2022-04-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_question_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcade',
            name='is_last_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='complete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
