# Generated by Django 4.0.3 on 2022-04-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_arcade_is_last_viewed_alter_history_complete_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arcade',
            name='created',
        ),
        migrations.AddField(
            model_name='arcade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
